name: CI‑CD to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: copilotlinebot
  NODE_VERSION: '20.x'

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: List files before packaging
        run: |
          echo "Working directory: $(pwd)"
          ls -R .

      - name: Archive project
        run: zip -r project.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: project
          path: project.zip

  deploy:
    name: Deploy to Azure Web App
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: project
          path: .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: project.zip

